Updates footer
rotationalio/rotational.io pull request #132
Opened 2023-02-24 14:44 UTC by daniellemaxwell

Updates the website footer as shown [here](https://www.figma.com/file/LNW4E3VcdnEgR7s1QO0gep/Rotational-Website-Refactor?node-id=744%3A37&t=t3xzNJZKq1uIJI9J-1).

Fixes SC-12012

Acceptance Criteria: 

https://www.awesomescreenshot.com/video/15092772?key=ace46c6169d4ef7b5119c0b7aefb9b9a

2023-02-24 19:21 UTC, masskoder approved these changes

2023-02-27 23:17 UTC, eschmier requested changes
@daniellemaxwell This looks good! My only request is to ask if it's possible to center the social media icons when the screen size is collapsed so it is consistent with the text above. 
See image. 
<img width="366" alt="Screen Shot 2023-02-27 at 6 12 15 PM" src="https://user-images.githubusercontent.com/2703255/221711150-92d2e22d-8018-47b6-8459-ff9bbc3a7c96.png">

2023-02-28 20:12 UTC, masskoder approved these changes

2023-03-01 14:34 UTC, daniellemaxwell commented
@eschmier When I centered the icons for smaller screens (widths less than 600), I noticed some shifting that made it the icons a little off. It looked fine at widths around 390, but shifted as the width increased. To prevent this, I used grid for the smaller screens so it should be more consistent now. Here's a video showing the changes: https://www.awesomescreenshot.com/video/15224125?key=d35f4ee6ddbe1ffcb2bf13976bc88455

2023-03-01 14:47 UTC, eschmier approved these changes
Thank you @daniellemaxwell That's a good solution!

2023-03-01 14:57 UTC, merged