homepage's chinese content
rotationalio/rotational.io pull request #38
Opened 2021-08-10 18:28 UTC by KNGJOEL

2021-08-10 19:05 UTC, KNGJOEL commented
![Screen Shot 2021-08-10 at 3 00 57 PM](https://user-images.githubusercontent.com/49071804/128919924-95232590-4eb2-4afa-8b04-7afeecc2693c.png)
![Screen Shot 2021-08-10 at 3 01 23 PM](https://user-images.githubusercontent.com/49071804/128919945-d917d784-5820-4b17-bdda-d6fa04819098.png)
![Screen Shot 2021-08-10 at 3 01 52 PM](https://user-images.githubusercontent.com/49071804/128919951-2a394dfc-3a2f-466d-a197-88fe8863d56f.png)
![Screen Shot 2021-08-10 at 3 02 04 PM](https://user-images.githubusercontent.com/49071804/128919959-ca6616e5-29a0-4d7a-a648-084928ad9321.png)
![Screen Shot 2021-08-10 at 3 02 16 PM](https://user-images.githubusercontent.com/49071804/128919964-63d9b5c9-9b7f-4306-bc17-0850c1171093.png)
![Screen Shot 2021-08-10 at 3 02 28 PM](https://user-images.githubusercontent.com/49071804/128919965-596295bc-4c2f-44ad-92f7-60e8943e2b26.png)
![Screen Shot 2021-08-10 at 3 02 52 PM](https://user-images.githubusercontent.com/49071804/128919969-c56ff603-0f22-4006-83aa-18b508958d30.png)

2021-08-10 22:07 UTC, rebeccabilbro commented
Thanks for working on making our home page available in Chinese @KNGJOEL! This seems like a strong start. 

@tl6kk &mdash; would you mind taking a look to see if everything seems ok? 

The main thing I'm noticing is that I think we prefer to use `zh` to `cn`.

To build the branch locally:

```bash
git clone git@github.com:rotationalio/rotational.io.git
cd rotationalio.github.io
git remote add KNGJOEL git@github.KNGJOEL/rotational.io.git
git fetch KNGJOEL
git checkout -b zh-home KNGJOEL/add-chinese-language-content-for-homepage
hugo serve -D
```

2021-08-11 09:32 UTC, tl6kk commented
Thanks for your work @KNGJOEL for our Chinese viewers! The page looks great. I only noticed a few small errors:

- Under "Consulting Services" ("咨询服务“), the last row, there is an extra I before 数据服务
- The GDS name are in Franch
- This is really minor, but under "Software Development" ("软件开发"), the last row misses some space. Ideally should be "云 & 分布式系统“
- Our Team ”我们的团队“, there is an extra N in the beginning.

Everything else looks great to me!

2021-08-11 10:31 UTC, KNGJOEL commented
Got it i'll solve it

On Wed, Aug 11, 2021, 9:33 AM tl6kk ***@***.***> wrote:

> Thanks for your work @KNGJOEL <https://github.com/KNGJOEL> for our
> Chinese viewers! The page looks great. I only noticed a few small errors:
>
>    - Under "Consulting Services" ("咨询服务“), the last row, there is an
>    extra I before 数据服务
>    - The GDS name are in Franch
>    - This is really minor, but under "Software Development" ("软件开发"), the
>    last row misses some space. Ideally should be "云 & 分布式系统“
>    - Our Team ”我们的团队“, there is an extra N in the beginning.
>
> Everything else looks great to me!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rotationalio/rotational.io/pull/38#issuecomment-896667056>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWMNPGEIGTTLVO5YMUGIGLT4I7VHANCNFSM5B4VBYEA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-11 16:01 UTC, rebeccabilbro requested changes
Thank you @tl6kk for catching those edits and @KNGJOEL for making those updates so quickly! There are a few other small requested changes I've noted in my review, but with these additional edits I think we should be able to merge soon and get this page live!

@KNGJOEL am I correct in assuming that we will need to merge #37 before we merge #38?

2021-08-11 16:18 UTC, KNGJOEL commented on data/zh/feature.yml
> +      content : Nous donnons aux développeurs un accès à une cohérence forte à un niveau supérieur de la pile d'applications, ajoutant flexibilité et visibilité à vos services de données gérés exista
Understood, I will

2021-08-11 16:19 UTC, KNGJOEL commented
> Thank you @tl6kk for catching those edits and @KNGJOEL for making those updates so quickly! There are a few other small requested changes I've noted in my review, but with these additional edits I think we should be able to merge soon and get this page live!
> 
> @KNGJOEL am I correct in assuming that we will need to merge #37 before we merge #38?

yes we will

2021-08-11 17:23 UTC, rebeccabilbro approved these changes

2021-08-11 17:23 UTC, merged